name: Generate Policy Release Notifications

on:
  # Trigger this workflow on pushes to master
  push:
    branches:
      # - master
      - POL-847-policy-automated-updates-on-releases

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch:
    branches:
  #     - master
      - POL-847-policy-automated-updates-on-releases
jobs:
  policy-release-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Speed up checkout by not fetching history

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Run Generate Policy Release Notification Content Script
        run: ruby tools/policy_template_release_generation/generate_policy_release_notifcation_contents.rb
